### ISSUE TITLE
打断点崩溃

### ISSUE THREAD

**Issue by Freshman111** [dongjunkun/BannerLayout#16]
@Override
        public Object instantiateItem(ViewGroup container, int position) {
            if (views.size() > 0) {
                //position % view.size()是指虚拟的position会在[0，view.size()）之间循环
                View view = views.get(position % views.size());
                if (container.equals(view.getParent())) {
                    container.removeView(view);
                }
                container.addView(view);
                return view;
            }
            return null;
        }

您好，我打断点打到container.addView(view);这句代码时直接跳转到return null;了然后app直接退出。不打断点事没事的。我不知道这是不是有什么隐患

**Comment by dongjunkun** [comment]
这个问题很有意思，和View的绘制有关系吧
