### ISSUE TITLE
向某侧微滑时，松手时会向反方向滑动两个View

### ISSUE THREAD

**Issue by chengdazhi** [dongjunkun/BannerLayout#17]
向某侧微滑时，松手时会向反方向滑动两个View

**Comment by chengdazhi** [comment]
问题找到，在ViewPager源码的determineTargetPage()方法中，如果position过大，会导致计算错误，原因怀疑是科学计数法相关，应把Integer.MAX_VALUE改成十万量级，就不会有这个问题了。

**Comment by dongjunkun** [comment]
已修复
