### ISSUE TITLE
你好，我找到一个小bug

### ISSUE THREAD

**Issue by iamsdk** [dongjunkun/BannerLayout#2]
有时候会出现连续滚动两张图的bug，然后我排查了一下，原因可能是因为多次startAutoPlay引起的，你可以测试一下，点击按钮运行一次startAutoPlay();就会出现了，然后这个是解决方法：
 /**
     \* 开始自动轮播
     */
    public void startAutoPlay() {
        if (isAutoPlay) {
            stopAutoPlay();//这句是我加上的
            handler.sendEmptyMessageDelayed(WHAT_AUTO_PLAY, autoPlayDuration);
        }
    }
应该在这个地方加上一句这个，然后就好了: )
顺便说一下，你这个很好使，谢谢么么哒~嗯嘛~强行怼你一下

**Comment by dongjunkun** [comment]
好的，马上修复

**Comment by iamsdk** [comment]
我可以加你秋秋好友吗：)有时间想学习一下有关自定义控件的
