### ISSUE TITLE
能否隐藏指示器呢

### ISSUE THREAD

**Issue by excitedhaha** [dongjunkun/BannerLayout#20]
比如在只有一个广告的时候，隐藏显示器，并且不能手动切换轮播图

**Comment by dongjunkun** [comment]
可以做吧，但是一般轮播图低于三种感觉没多大意义，只用显示一个ImageView即可

**Comment by excitedhaha** [comment]
我们的轮播图数量是不确定的，由服务端控制

**Comment by dongjunkun** [comment]
你的需求实现起来还是很简单的，只需要判断返回的图片数量是否为1，为1的时候隐藏BannerLayout使用一个ImageView代替即可，如果觉得这个比较常见，也可以封装到控件里面去

**Comment by excitedhaha** [comment]
这也是个解决办法，谢谢
