### ISSUE TITLE
关于加载失败设置默认本地图像不起作用问题 

### ISSUE THREAD

**Issue by Ordosbxy** [dongjunkun/BannerLayout#3]
现在加载失败后，是一张空白图片，一般需要设置一张带产品logo的图片，希望作者考虑一下这个因素。我直接在BannerLayout中添加这两句，但是不起作用
        Glide.with(getContext())
                .load(res)
                .placeholder(R.drawable.banner_place_holder)
                .error(R.drawable.banner_place_holder)
                .centerCrop().into(imageView);

**Comment by dongjunkun** [comment]
应该是修改错了地方，上面的代码是加载本地的图片，还有一个地方是加载网络图片的

**Comment by Ordosbxy** [comment]
谢谢。确实应该加在另外一个getImageView(String url，......) 方法中

**Comment by gnkhandsome** [comment]
这个问题怎么解决啊
