### ISSUE TITLE
2G网，会出现闪退~

### ISSUE THREAD

**Issue by iamsdk** [dongjunkun/BannerLayout#5]
用了好久测试出来的，低网速模式下会闪退

**Comment by dongjunkun** [comment]
能不能将错误信息贴出来呢

**Comment by iamsdk** [comment]
错误信息是找不到了。用户反馈的，我捕捉不到错误信息，不过错误是确实存在的，今天来一看你的更新信息，说是把低网速下的闪退bug解决了，重新下载下来试试
