### ISSUE TITLE
为什么点击banner时候会向左滚动，点击事件就收不到了

### ISSUE THREAD

**Issue by jackuhan** [dongjunkun/BannerLayout#8]
快速往右滑动，点击banner，则自动向左滑动。代码看不出问题

**Comment by dongjunkun** [comment]
可以将 app:scrollDuration="1100"的默认值设置小一点比如900

**Comment by jackuhan** [comment]
代码中已经是900了
我暂时设置了200就行了，这个bug是如何产生的？

**Comment by jackuhan** [comment]
我暂时设置了200就行了，这个bug是如何产生的？

**Comment by jackuhan** [comment]
加我qq 1196681436，等会删
