### ISSUE TITLE
Binary XML file line #26: Error inflating class com.yyydjk.library.BannerLayout

### ISSUE THREAD

**Issue by onlycyndi** [dongjunkun/BannerLayout#9]
java.lang.NumberFormatException: Attribute '?attr/colorPrimary' not found. Are you using the right theme?

**Comment by onlycyndi** [comment]
你好，加到布局的时候提示Attribute找不到，运行的时候就闪退了，请问下这个怎么解决啊？

**Comment by jp0533** [comment]
同遇这个问题
